/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Trip model module.
 * @module model/Trip
 * @version 1.0.0
 */
class Trip {
    /**
     * Constructs a new <code>Trip</code>.
     * @alias module:model/Trip
     * @param tripTitle {String} 
     */
    constructor(tripTitle) { 
        
        Trip.initialize(this, tripTitle);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, tripTitle) { 
        obj['TripTitle'] = tripTitle;
    }

    /**
     * Constructs a <code>Trip</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Trip} obj Optional instance to populate.
     * @return {module:model/Trip} The populated <code>Trip</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Trip();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('TripTitle')) {
                obj['TripTitle'] = ApiClient.convertToType(data['TripTitle'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Trip.prototype['_id'] = undefined;

/**
 * @member {String} TripTitle
 */
Trip.prototype['TripTitle'] = undefined;






export default Trip;

